failure-threshold: info
format: tty
ignored: [ ]
no-color: true
no-fail: false
override:
  error: [ ]
  warning: [ ]
  info: [ ]
  style: [ ]
strict-labels: false
disable-ignore-pragma: true
trustedRegistries:
  - docker.io
